#!/bin/sh

if [[ $1 == install ]]; then

echo "Backup//Respaldando Hosts"
mkdir /etc/BackupHosts
cp -a /etc/hosts /etc/BackupHosts/originalhosts
exit 0

fi

if [[ $1 == upgrade && $2 == 7.2 || $1 == upgrade && $2 == 7.1 ]]; then

echo "Upgrade//Actualizando"
mkdir /etc/BackupHosts
cp -a /etc/MinimalHostsBlocker/hostsstock /etc/BackupHosts/originalhosts
exit 0

fi
